apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: prometheus-ingress
    namespace: prometheus
  spec:
    rules:
    - host: zt.prometheus.io
      http:
        paths:
        - backend:
            serviceName: prometheus-svc
            servicePort: 9090
          path: /